### ISSUE TITLE
setup-dhall fails with Cannot read properties of undefined (reading 'browser_download_url')

### ISSUE THREAD

**Issue by TristanCacqueray** [dhall-lang/setup-dhall#8]
It seems like the action is broken by failing with:

```
Run dhall-lang/setup-dhall@v4
  with:
    version: latest
Fetching dhall releases from https://api.github.com/repos/dhall-lang/dhall-haskell/releases/latest
/home/runner/work/_actions/dhall-lang/setup-dhall/v4/src/action.js:61
    core: coreRelease.browser_download_url,
                      ^

TypeError: Cannot read properties of undefined (reading 'browser_download_url')
    at fetchReleases (/home/runner/work/_actions/dhall-lang/setup-dhall/v4/src/action.js:61:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/_actions/dhall-lang/setup-dhall/v4/src/action.js:104:16)
```

Example run: https://github.com/change-metrics/demo-node-config/actions/runs/7453463971/job/20278886176?pr=8

**Comment by thoughtpolice** [comment]
For anyone running into this, the problem is that Dhall 1.42.1 has no release assets, so the attempt to download the assets in the action fails. You can fix this by specifying:

```
      - uses: dhall-lang/setup-dhall@v4
        with:
          version: '1.42.0'
```

to work around it

**Comment by craig-day** [comment]
Thanks for the workaround @thoughtpolice, looks like this is blocked until https://github.com/dhall-lang/dhall-haskell/issues/2564 is resolved.
